# Core
core_similarity_original = Original
core_similarity_very_high = Muito alto
core_similarity_high = Alto
core_similarity_medium = Médio
core_similarity_small = Pequeno
core_similarity_very_small = Muito pequeno
core_similarity_minimal = Mínimo
core_cannot_open_dir = Não foi possível abrir o diretório ‘{ $dir }’, por causa de ‘{ $reason }’
core_cannot_read_entry_dir = Não foi possível ler a entrada do diretório ‘{ $dir }’, por causa de ‘{ $reason }’
core_cannot_read_metadata_dir = Não foi possível ler os metadados no diretório ‘{ $dir }’, por causa de ‘{ $reason }’
core_file_modified_before_epoch = O arquivo ‘{ $name }’ parece ter sido modificado antes do ‘Epoch’ do Unix
core_folder_modified_before_epoch = A pasta ‘{ $name }’ parece ter sido modificada antes do ‘Epoch’ do Unix
core_file_no_modification_date = Não foi possível obter a data da modificação do arquivo ‘{ $name }’, por causa de ‘{ $reason }’
core_folder_no_modification_date = Não foi possível obter a data da modificação da pasta ‘{ $name }’, por causa de ‘{ $reason }’
core_missing_no_chosen_included_directory = Pelo menos um diretório deve ser informado
core_directory_must_exists = Sobre os diretórios. A pasta fornecida deve existir no caminho ‘{ $path }’ e será ignorada
core_directory_must_be_directory = Sobre os diretórios. Os diretórios do caminho ‘{ $path }’ que foi fornecido deve apontar para um diretório e será ignorado
core_included_directory_zero_valid_directories = Ocorreu um erro ao incluir um diretório. Não foi encontrado nenhum caminho correto para incluir um diretório
core_excluded_directory_pointless_slash = Sobre os diretórios. A ação de ‘Excluir’ não faz sentido, porque significa que nenhum arquivo será pesquisado
core_directory_overlap = Sobre os diretórios. Todos os diretórios a serem pesquisados se sobrepõem aos diretórios que foram excluídos
core_directory_unable_to_get_device_id = Sobre os diretórios. Não foi possível obter o dispositivo de ajuda da pasta ‘{ $path }’
core_ffmpeg_not_found = Não foi possível encontrar a instalação adequada do ‘FFmpeg’, este é um programa externo, que você precisa instalar manualmente.
core_ffmpeg_not_found_windows = Certifique-se de que o ‘ffmpeg.exe’ e ‘ffprobe.exe’ estejam disponíveis no caminho ou sejam colocados diretamente na mesma pasta onde está o executável do programa
core_invalid_symlink_infinite_recursion = Ocorreu um erro de execução na recursão infinita
core_invalid_symlink_non_existent_destination = O arquivo de destino não existe
rust_error_moving_to_trash = Ocorreu um erro ao mover o arquivo ‘{ $file }’ para a lixeira, por causa do erro { $error }
rust_error_removing = Ocorreu um erro ao remover o arquivo ‘{ $file }’, por causa do erro { $error }
