# Core
core_similarity_original = Original
core_similarity_very_high = Muito grande
core_similarity_high = Grande
core_similarity_medium = Médio
core_similarity_small = Pequeno
core_similarity_very_small = Muito pequeno
core_similarity_minimal = Mínimo
core_cannot_open_dir = Não foi possível abrir o diretório ‘{ $dir }’, por causa de ‘{ $reason }’
core_cannot_read_entry_dir = Não foi possível ler os dados do diretório ‘{ $dir }’, por causa de ‘{ $reason }’
core_cannot_read_metadata_dir = Não foi possível ler os metadados do diretório ‘{ $dir }’, por causa de ‘{ $reason }’
core_cannot_read_metadata_file = Não foi possível ler os metadados no arquivo ‘{ $file }’, por causa de ‘{ $reason }’
core_file_modified_before_epoch = O arquivo ‘{ $name }’ parece ter sido modificado antes do ‘Epoch’ do Unix
core_folder_modified_before_epoch = A pasta ‘{ $name }’ parece ter sido modificada antes do ‘Epoch’ do Unix 
core_file_no_modification_date = Não foi possível obter a data da modificação do arquivo ‘{ $name }’, por causa de ‘{ $reason }’
core_folder_no_modification_date = Não foi possível obter a data da modificação da pasta ‘{ $name }’, por causa de ‘{ $reason }’
core_missing_no_chosen_included_path = Nenhum caminho válido foi selecionado (os caminhos que foram excluídos poderiam ter excluído todos os caminhos que haviam sido incluídos)
core_reference_included_paths_same = Não foi possível iniciar a verificação porque todos os caminhos válidos que foram incluídos também são caminhos referenciados. Tente ativar ou desativar os caminhos referenciados
core_path_must_exists = O caminho que foi fornecido tem que apontar para um diretório, por tanto, o caminho ‘{ $path }’ será ignorado
core_must_be_directory_or_file = O caminho que foi fornecido tem que apontar para um diretório ou para um arquivo válido, por tanto, o caminho ‘{ $path }’ será ignorado
core_excluded_paths_pointless_slash = Se você excluir a barra ‘ / ’, significa que nenhum arquivo será verificado
core_paths_unable_to_get_device_id = Não foi possível obter o ID (identificador) do dispositivo da pasta ‘{ $path }’
core_needs_allowed_extensions_limited_by_tool = Não foi possível iniciar a verificação porque todas as extensões ‘{ $extensions }’ que estão disponíveis nesta ferramenta foram excluídas da verificação
core_needs_allowed_extensions = Não foi possível iniciar a verificação porque todas as extensões foram excluídas da verificação
core_needs_to_set_at_least_one_broken_option = Não foi possível iniciar a verificação porque nenhuma opção do nome corrompido foi definida para ser verificada
core_needs_to_set_at_least_one_bad_name_option = Não foi possível iniciar a verificação porque nenhuma opção do nome incorreto foi definida para ser verificada
core_ffmpeg_not_found = Não foi possível encontrar a instalação dos programas ‘FFmpeg’ ou ‘FFprobe’. Estes programas são externos e você tem que ser instalá-los manualmente.
core_ffmpeg_not_found_windows = Certifique-se de que o ‘ffmpeg.exe’ e ‘ffprobe.exe’ estejam disponíveis no caminho ou sejam colocados diretamente na mesma pasta onde está o executável do programa
core_invalid_symlink_infinite_recursion = Ocorreu um erro de execução na recursão infinita
core_invalid_symlink_non_existent_destination = O arquivo de destino não existe
core_messages_limit_reached_characters = A quantidade de ‘{ $current }’ caracteres na mensagem excedeu o limite de ‘{ $limit }’ que foi definido, portanto, a saída foi truncada. Para ler a saída completa, desative a opção do limite de caracteres nas configurações.
core_messages_limit_reached_lines = A quantidade de ‘{ $current }’ linhas na mensagem excedeu o limite de ‘{ $limit }’ que foi definido, portanto, a saída foi truncada. Para ler a saída completa, desative a opção do limite de linhas nas configurações.
core_error_moving_to_trash = Ocorreu o erro ‘{ $error }’ ao tentar mover o arquivo ‘{ $file }’ para a lixeira
core_error_removing = Ocorreu o erro ‘{ $error }’ ao tentar remover o arquivo ‘{ $file }’
core_no_similarity_method_selected = Não foi possível encontrar os arquivos de música equivalentes porque um método de equivalência não foi definido
