# In Rust translations
rust_loaded_preset = A predefinição ‘{ $preset_idx }’ foi carregada
rust_file_already_exists = O arquivo ‘{ $file }’ já existe e não será sobrescrito
rust_error_removing_file_after_copy = Ocorreu um erro ao remover o arquivo ‘{ $file }’ (depois de copiar para uma partição diferente) por causa de ‘{ $reason }’
rust_error_copying_file = Ocorreu um erro ao copiar ‘{ $input }’ para ‘{ $output }’ por causa de ‘{ $reason }’
rust_loading_tags_cache = Carregando o ‘cache’ das informações dos arquivos
rust_loading_fingerprints_cache = Carregando o ‘cache’ das impressões digitais
rust_saving_tags_cache = Salvando o ‘cache’ das informações dos arquivos
rust_saving_fingerprints_cache = Salvando o ‘cache’ das impressões digitais
rust_loading_prehash_cache = Carregando o ‘cache’ da integridade inicial do arquivo
rust_saving_prehash_cache = Salvando o ‘cache’ da integridade inicial do arquivo
rust_loading_hash_cache = Carregando o ‘cache’ da integridade do arquivo
rust_saving_hash_cache = Salvando o ‘cache’ da integridade do arquivo
rust_loading_exif_cache = Carregando o ‘cache’ do EXIF
rust_saving_exif_cache = Salvando o ‘cache’ do EXIF
rust_scanning_name = Verificando o nome do arquivo ‘{ $entries_checked }’
rust_scanning_size_name = Verificando o tamanho e o nome do arquivo ‘{ $entries_checked }’
rust_scanning_size = Verificando o tamanho do arquivo ‘{ $entries_checked }’
rust_scanning_file = Verificando o arquivo ‘{ $entries_checked }’
rust_scanning_folder = Verificando a pasta ‘{ $entries_checked }’
rust_checked_tags = As informações dos ‘{ $items_stats }’ arquivos foram verificadas
rust_checked_content = O conteúdo de ‘{ $items_stats }’ foi verificado de ‘{ $size_stats }’
rust_compared_tags = As informações dos ‘{ $items_stats }’ arquivos foram comparadas
rust_compared_content = O conteúdo de ‘{ $items_stats }’ foi comparado
rust_hashed_images = As informações de ‘{ $items_stats }’ arquivos ‘hash’ das imagens ‘{ $size_stats }’
rust_compared_image_hashes = Foram comparados ‘{ $items_stats }’ os arquivos ‘hash’ das imagens
rust_hashed_videos = As informações dos ‘{ $items_stats }’ arquivos de vídeos
rust_created_thumbnails = Foram criadas ‘{ $items_stats }’ miniaturas dos arquivos de vídeo
rust_checked_files = O arquivo ‘{ $items_stats }’ foi verificado de ‘{ $size_stats }’
rust_checked_files_bad_extensions = O arquivo ‘{ $items_stats }’ foi verificado
rust_checked_images = Foram verificados ‘{ $items_stats }’ arquivos de imagens de ‘{ $size_stats }’
rust_checked_videos = Foram verificados ‘{ $items_stats }’ arquivos de vídeos de ‘{ $size_stats }’
rust_analyzed_partial_hash = As informações parciais dos ‘{ $items_stats } arquivos’ foram analisadas de ‘{ $size_stats }’
rust_analyzed_full_hash = As informações completas dos ‘{ $items_stats }’ arquivos foram analisadas de ‘{ $size_stats }’
rust_failed_to_rename_file = Ocorreu uma falha ao renomear o arquivo ‘{ $old_path }’ para ‘{ $new_path }’, por causa do erro ‘{ $error }’
rust_no_included_directories = Não é possível iniciar a verificação até que algum diretório seja incluído.
rust_all_dirs_referenced = Não é possível iniciar a verificação quando todos os diretórios incluídos estão definidos como pastas referenciadas.
rust_found_empty_folders = Foram encontradas ‘{ $items_found }’ pastas vazias. A verificação durou ‘{ $time }’
rust_found_empty_files = Foram encontrados ‘{ $items_found }’ arquivos vazios. A verificação durou ‘{ $time }’
rust_found_similar_images = Foram encontrados ‘{ $items_found }’ arquivos de imagem equivalentes nos ‘{ $groups }’ grupos. A verificação durou ‘{ $time }’
rust_found_similar_videos = Foram encontrados ‘{ $items_found }’ arquivos de vídeo equivalentes nos ‘{ $groups }’ grupos. A verificação durou ‘{ $time }’
rust_no_similarity_method_selected = Não é possível encontrar arquivos de música equivalentes sem que um método de equivalência seja selecionado.
rust_found_similar_music_files = Foram encontrados ‘{ $items_found }’ arquivos de músicas equivalentes nos ‘{ $groups }’ grupos. A verificação durou ‘{ $time }’
rust_found_invalid_symlinks = Foram encontradas ‘{ $items_found }’ ligações simbólicas que não são válidas. A verificação durou ‘{ $time }’
rust_found_temporary_files = Foram encontrados ‘{ $items_found }’ arquivos temporários. A verificação durou ‘{ $time }’
rust_no_file_type_selected = Não é possível encontrar os arquivos danificados sem que o tipo do arquivo seja selecionado.
rust_found_broken_files = Foram encontrados ‘{ $items_found }’ arquivos danificados que ocupam { $size } de espaço. A verificação durou ‘{ $time }’
rust_found_bad_extensions = Foram encontrados ‘{ $items_found }’ arquivos com extensões problemáticas. A verificação durou ‘{ $time }’
rust_found_video_optimizer = Foram encontrados ‘{ $items_found }’ arquivos para serem otimizados. A verificação durou ‘{ $time }’
rust_found_duplicate_files = Foram encontrados ‘{ $items_found }’ arquivos duplicados nos { $groups } grupos. A verificação durou ‘{ $time }’
rust_found_duplicate_files_no_lost_space = Foram encontrados ‘{ $items_found }’ arquivos duplicados nos { $groups } grupos. A verificação durou ‘{ $time }’
rust_found_big_files = Foram encontrados ‘{ $items_found }’ arquivos grandes com tamanho de { $size }. A verificação durou ‘{ $time }’
rust_found_exif_files = Foram encontrados ‘{ $items_found }’ arquivos com dados do tipo ‘EXIF’. A verificação durou ‘{ $time }’
rust_cannot_load_preset = Não foi possível alterar e carregar a predefinição ‘{ $preset_idx }’ por causa de ‘{ $reason }’, por tanto, será utilizado as configurações padrão
rust_saved_preset = A predefinição ‘{ $preset_idx }’ foi salva com sucesso
rust_cannot_save_preset = Não foi possível salvar a predefinição ‘{ $preset_idx }’ por causa de ‘{ $reason }’
rust_reset_preset = Redefinir a predefinição ‘{ $preset_idx }’
rust_cannot_create_output_folder = Não foi possível criar a pasta de saída ‘{ $output_folder }’ por causa do erro ‘{ $error }’
rust_delete_summary = Foram excluídos ‘{ $deleted }’ itens, ocorreu uma falha ao remover ‘{ $failed }’ itens de ‘{ $total }’ itens
rust_rename_summary = Foram renomeados ‘{ $renamed }’ itens, ocorreu uma falha ao renomear ‘{ $failed }’ itens de ‘{ $total }’ itens
rust_move_summary = Foram movidos ‘{ $moved }’ itens, ocorreu uma falha ao mover ‘{ $failed }’ itens  para fora de ‘{ $total }’ itens
rust_hardlink_summary = Foram criadas ‘{ $hardlinked }’ ligações rígidas, ocorreu uma falha ao ligar ou vincular ‘{ $failed }’ itens de ‘{ $total }’ itens
rust_symlink_summary = Foram criadas ‘{ $symlinked }’ ligações simbólicas, ocorreu uma falha ao ligar ou vincular ‘{ $failed }’ itens de ‘{ $total }’ itens
rust_optimize_video_summary = Foram otimizados ‘{ $optimized }’ vídeos, ocorreu uma falha ao otimizar ‘{ $failed }’ vídeos de ‘{ $total }’ vídeos
rust_clean_exif_summary = Foram removidos ‘{ $cleaned }’ arquivos com o ‘EXIF’, ocorreu uma falha ao remover ‘{ $failed }’ arquivos de ‘{ $total }’ itens
rust_deleting_files = Excluindo ‘{ $items_stats }’ arquivo(s) de { $size_stats }
rust_deleting_no_size_files = Excluindo o arquivo ‘{ $items_stats }’
rust_renaming_files = Renomeando o arquivo ‘{ $items_stats }’
rust_moving_files = Movendo ‘{ $items_stats }’ arquivos de ‘{ $size_stats }’
rust_moving_no_size_files = Movendo o arquivo ‘{ $items_stats }’
rust_hardlinking_files = Criando ‘{ $items_stats }’ ligações rígidas de ‘{ $size_stats }’ arquivos
rust_hardlinking_no_size_files = Criando ‘{ $items_stats }’ ligações rígidas do arquivo
rust_symlinking_files = Criando ‘{ $items_stats }’ ligações simbólicas de ‘{ $size_stats }’ arquivos
rust_symlinking_no_size_files = Criando ‘{ $items_stats }’ ligações simbólicas do arquivo
rust_optimizing_videos = Foram otimizados ‘{ $items_stats }’ vídeos de ‘{ $size_stats }’ arquivos
rust_optimizing_no_size_videos = Foram otimizados ‘{ $items_stats }’ vídeos
rust_cleaning_exif = Removendo o ‘EXIF’ dos ‘{ $items_stats }’ arquivos de ‘{ $size_stats }’ arquivos
rust_cleaning_no_size_exif = Removendo o ‘EXIF’ do arquivo ‘{ $items_stats }’
rust_no_files_deleted = Nenhum arquivo ou pasta foi selecionado para ser excluído
rust_no_files_renamed = Nenhum arquivo ou pasta foi selecionado para ser renomeado
rust_no_files_moved = Nenhum arquivo ou pasta foi selecionado para ser movido
rust_no_files_hardlinked = Nenhum arquivo ou pasta foi selecionado para a criação da ligação rígida
rust_no_files_symlinked = Nenhum arquivo ou pasta foi selecionado para a criação da ligação simbólica
rust_no_videos_optimized = Nenhum arquivo de vídeo foi selecionado para ser otimizado
rust_no_exif_cleaned = Nenhum arquivo foi selecionado para ser removido os ‘EXIF’
rust_extracted_exif_tags = Os ‘EXIF’ foram extraídos de ‘{ $items_stats }’ arquivos de { $size_stats }
rust_delete_confirmation = Você tem certeza de que quer excluir os itens que foram selecionados?
rust_delete_confirmation_number_simple = { $items } itens foram selecionados.
rust_delete_confirmation_number_groups = { $items } itens foram selecionados nos { $groups } grupos.
rust_delete_confirmation_selected_all_in_group = Todos os itens foram selecionados nos { $groups } grupos.
rust_move_confirmation = Você tem certeza de que quer mover os itens que foram selecionados?
rust_move_confirmation_number_simple = { $items } itens foram selecionados.
rust_clean_exif_confirmation = Você tem certeza de que quer remover os dados ‘EXIF’ dos itens que foram selecionados?
rust_clean_exif_confirmation_number_simple = { $items } itens foram selecionados.
clean_exif_overwrite_files_text = Sobrescrever os arquivos
rust_optimize_video_confirmation = Você tem certeza de que quer otimizar os arquivos de vídeos que foram selecionados?
rust_optimize_video_confirmation_number_simple = { $items } itens foram selecionados.
rust_hardlink_confirmation = Você tem certeza de que quer criar as ligações rígidas para os itens que foram selecionados?
rust_hardlink_confirmation_number_simple = { $items } itens foram selecionados.
rust_symlink_confirmation = Você tem certeza de que quer criar as ligações simbólicas para os itens que foram selecionados?
rust_symlink_confirmation_number_simple = { $items } itens foram selecionados.
rust_rename_confirmation = Você tem certeza de que quer renomear os itens que foram selecionados?
rust_rename_confirmation_number_simple = { $items } itens foram selecionados.

# Slint translations, but in arrays

column_selection = Seleção
column_size = Tamanho
column_file_name = Nome do arquivo
column_path = Caminho
column_modification_date = Data da modificação
column_similarity = Equivalentes
column_dimensions = Dimensões
column_title = Título
column_artist = Artista
column_year = Ano
column_bitrate = Taxa de bits
column_length = Comprimento
column_genre = Gênero
column_type_of_error = Tipo do erro
column_symlink_name = Nome da ligação simbólica
column_symlink_folder = Pasta da ligação simbólica
column_destination_path = Caminho do destino
column_current_extension = Extensão atual
column_proper_extension = Extensão corrompida
column_fps = FPS
column_codec = Codec
column_duration = Duração
column_exif_tags = Identificadores EXIF
# Slint translations
ok_button = Ok
cancel_button = Cancelar
do_you_want_to_continue = Você quer continuar?
main_window_title = Limpador de Dados do Krokiet
scan_button = Verificar
stop_button = Interromper
select_button = Selecionar
move_button = Mover
delete_button = Excluir
save_button = Salvar
sort_button = Ordenar
rename_button = Renomear
motto = Este programa é e sempre será de uso gratuito.\nPor favor, consulte a licença do MIT/GPL para obter mais informações.
unicorn = Você pode até não olhar para o unicórnio, mas o unicórnio sempre está olhando para você.
repository = Repositório
instruction = Instruções
donation = Faça uma doação
translation = Tradução
included_directories = Diretórios incluídos
excluded_directories = Diretórios excluídos
ref = Referência
path = Caminho
tool_duplicate_files = Arquivos duplicados
tool_empty_folders = Pastas vazias
tool_big_files = Arquivos grandes
tool_empty_files = Arquivos vazios
tool_temporary_files = Arquivos temporários
tool_similar_images = Imagens equivalentes
tool_similar_videos = Vídeos equivalentes
tool_music_duplicates = Músicas duplicadas
tool_invalid_symlinks = Ligações simbólicas inválidas
tool_broken_files = Arquivos corrompidos
tool_bad_extensions = Extensões inválidas
tool_video_optimizer = Otimizador de vídeo
tool_exif_remover = Removedor de EXIF
sort_by_full_name = Ordenar por nome completo
sort_by_selection = Ordenar por seleção
sort_reverse = Ordenar inversamente
selection_all = Selecionar todos
selection_deselect_all = Desselecionar todos
selection_invert_selection = Inverter a seleção
selection_the_biggest_size = Selecionar o maior tamanho
selection_the_biggest_resolution = Selecionar a maior resolução
selection_the_smallest_size = Selecionar o menor tamanho
selection_the_smallest_resolution = Selecionar a menor resolução
selection_newest = Selecionar o mais recente
selection_oldest = Selecionar o mais antigo
stage_current = Etapa atual:
stage_all = Todas as etapas:
subsettings = Subconfigurações
subsettings_images_hash_size = Tamanho do hash (verificação da integridade)
subsettings_images_resize_algorithm = Redimensionar o algoritmo
subsettings_images_ignore_same_size = Ignorar as imagens com o mesmo tamanho
subsettings_images_max_difference = Diferença máxima
subsettings_images_duplicates_hash_type = Tipo do hash (verificação da integridade)
subsettings_duplicates_check_method = Método de verificação
subsettings_duplicates_name_case_sensitive = Diferenciar as letras maiúsculas das minúsculas (somente para o modo por nome)
subsettings_biggest_files_sub_method = Método
subsettings_biggest_files_sub_number_of_files = Quantidade de arquivos
subsettings_videos_max_difference = Diferença máxima
subsettings_videos_ignore_same_size = Ignorar os vídeos com o mesmo tamanho
subsettings_music_audio_check_type = Tipo de verificação por áudio
subsettings_music_approximate_comparison = Comparação aproximada das informações dos arquivos
subsettings_music_compared_tags = As informações dos arquivos foram comparadas
subsettings_music_title = Título
subsettings_music_artist = Artista
subsettings_music_bitrate = Taxa de bits
subsettings_music_genre = Gênero
subsettings_music_year = Ano
subsettings_music_length = Comprimento
subsettings_music_max_difference = Diferença máxima
subsettings_music_minimal_fragment_duration = Duração mínima do fragmento
subsettings_music_compare_fingerprints_only_with_similar_titles = Comparar nos grupos por títulos equivalentes
subsettings_broken_files_type = Tipo dos arquivos para serem verificados
subsettings_broken_files_audio = Áudio
subsettings_broken_files_pdf = PDF
subsettings_broken_files_archive = Arquivo
subsettings_broken_files_image = Imagem
settings_global_settings = Configurações globais
settings_dark_theme = Tema escuro
settings_show_only_icons = Exibir somente os ícones
settings_excluded_items = Item que foi excluído:
settings_allowed_extensions = Extensões permitidas:
settings_excluded_extensions = Extensões excluídas:
settings_file_size = Tamanho do arquivo (em quilobytes)
settings_minimum_file_size = Mínimo:
settings_maximum_file_size = Máximo:
settings_recursive_search = Pesquisa recursiva
settings_use_cache = Utilizar o ‘cache’
settings_save_as_json = Também salvar o ‘cache’ como um arquivo JSON
settings_move_to_trash = Excluir permanentemente os arquivos que foram movidos para a lixeira
settings_ignore_other_filesystems = Ignorar os outros sistemas de arquivos (somente para o GNU/Linux)
settings_thread_number = Número do tópico
settings_restart_required = --- Você precisa reiniciar o programa para aplicar as alterações do número do tópico ---
settings_duplicate_image_preview = Pré-visualização da imagem
settings_duplicate_hide_hard_links = Ocultar as ligações rígidas
settings_duplicate_minimal_hash_cache_size = Tamanho mínimo dos arquivos no ‘cache’ das informações dos arquivos (KB)
settings_duplicate_use_prehash = Utilizar as informações iniciais do arquivo
settings_duplicate_minimal_prehash_cache_size = Tamanho mínimo dos arquivos no ‘cache’ das informações iniciais dos arquivos (KB)
settings_duplicate_delete_outdated_entries = Excluir automaticamente as entradas que estão desatualizadas
settings_similar_images_show_image_preview = Pré-visualização da imagem
settings_application_scale_text = Ajustar o tamanho da janela
settings_application_scale_hint_text = Ajustar manualmente o tamanho da janela (por exemplo, 1.0 = 100%)
settings_restart_required_scale_text = ---Você precisa reiniciar o programa para aplicar as alterações do tamanho da janela
settings_use_manual_application_scale_text = Utilizar o tamanho manual da janela
settings_similar_videos_generate_thumbnail_grid_instead_of_single_image_hint_text = Gerar uma grade para exibir várias imagens em miniaturas em vez de exibir uma única imagem (esta opção pode demorar mais)
settings_similar_images_hide_hard_links = Ocultar as ligações rígidas
settings_delete_outdated_entries = Excluir automaticamente as entradas que estão desatualizadas
settings_similar_videos_hide_hard_links = Ocultar as ligações rígidas
settings_similar_videos_image_preview = Pré-visualização da imagem
settings_similar_videos_generate_thumbnail_grid_instead_of_single_image = Exibir várias imagens em miniaturas
settings_open_config_folder = Abrir a pasta das configurações
settings_open_cache_folder = Abrir a pasta do ‘cache’
settings_language = Idioma
settings_current_preset = Predefinição atual:
settings_edit_name = Editar o nome
settings_choose_name_for_prefix = Escolha o nome para o prefixo
settings_save = Salvar
settings_load = Carregar
settings_reset = Redefinir
settings_similar_videos_tool = Ferramenta dos vídeos equivalentes
settings_similar_images_tool = Ferramenta das imagens equivalentes
settings_similar_music_tool = Ferramenta das músicas equivalentes
settings_general_settings = Configurações gerais
settings_settings = Configurações
settings_load_tabs_sizes_at_startup = Carregar por tamanho as abas ou guias na inicialização
settings_load_windows_size_at_startup = Carregar por tamanho as janelas na inicialização
settings_limit_lines_of_messages = Limitar a quantidade de mensagens exibidas em 500 linhas (esta é uma solução para resolver os problemas de lentidão)
settings_similar_videos_clear_unused_thumbnails = Excluir as miniaturas dos vídeos que não são utilizados com mais de 7 dias ao iniciar o programa
popup_save_title = Salvando os resultados
popup_save_message = Esta ação irá salvar os resultados em três arquivos diferentes
popup_rename_title = Renomeando os arquivos
popup_new_directories_title = Por favor, adicione os diretórios um em cada linha
popup_move_title = Movendo os arquivos
popup_move_copy_checkbox = Copiar os arquivos em vez de movê-los
popup_move_preserve_folder_checkbox = Preservar a estrutura das pastas
move_confirmation_text = Você tem certeza de que quer mover os itens que foram selecionados?
rename_confirmation_text = Você tem certeza de que quer renomear os itens que foram selecionados?
delete = Remover os itens
stopping_scan = Por favor, aguarde a interrupção da verificação.
searching = Pesquisando...
subsettings_videos_crop_detect = Método de detecção do corte
subsettings_videos_skip_forward_amount = Pular a duração [s]
subsettings_videos_vid_hash_duration = Duração do ‘hash’ (integridade do arquivo) de vídeo
subsettings_videos_thumbnail_percentage = Posição da miniatura no vídeo (%)
settings_cache_number_size_text = Tamanho do arquivo do ‘cache’: { $size }, quantidade de arquivos: { $number }
settings_video_thumbnails_number_size_text = Tamanho das miniaturas dos vídeo: { $size }, quantidade de arquivos: { $number }
settings_log_number_size_text = Tamanho dos arquivos do registro das alterações: { $size }, quantidade de arquivos: { $number }
subsettings_video_optimizer_mode = Modo
subsettings_video_optimizer_video_codec = Codec do vídeo
subsettings_video_optimizer_excluded_codecs = Codecs excluídos
subsettings_video_optimizer_video_quality = Qualidade do vídeo (CRF)
subsettings_video_optimizer_image_threshold = Limite da imagem
subsettings_reset = Redefinir
subsettings_exif_ignored_tags_text = Informações ignoradas:
subsettings_exif_ignored_tags_hint_text = Lista das informações dos arquivos que foram separadas por vírgulas para excluir da verificação (por exemplo, GPS, Thumbnail ou Miniatura). Algumas informações dos arquivos, como ImageWidth (largura da imagem) nos arquivos TIFF, são ocultadas para evitar que o arquivo da imagem seja corrompido.
clean_button_text = Remover
clean_text = Remover os dados EXIF
clean_confirmation_text = Você tem certeza de que quer remover os dados ‘EXIF’ dos itens que foram selecionados?
optimize_button_text = Otimizar
optimize_text = Otimizar as imagens
optimize_confirmation_text = Você tem certeza de que quer otimizar os itens que foram selecionados?
optimize_fail_if_bigger_text = Ignorar se o arquivo que foi otimizado for maior
optimize_overwrite_files_text = Sobrescrever os arquivos
optimize_limit_video_size_text = Limitar tamanho do vídeo
optimize_max_width_text = Largura máxima:
optimize_max_height_text = Altura máxima:
hardlink_button_text = Ligação simbólica rígida
hardlink_text = Criar as ligações simbólicas rígidas
hardlink_confirmation_text = Você tem certeza de que quer criar a ligação rígida (hardlinks) para os itens que foram selecionados?
softlink_button_text = Ligação simbólica
softlink_text = Criar softlinks
softlink_confirmation_text = Você tem certeza de que quer criar a ligação simbólica (softlinks ou symlinks) para os itens que foram selecionados?
